### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by lmanchon** [UofABioinformaticsHub/fastqcRShiny#5]
--
install not working with R 3.6.3:
BiocManager::install('UofABioinformaticsHub/shinyNgsreports')
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.3 (2020-02-29)
Installing github package(s) 'UofABioinformaticsHub/shinyNgsreports'
Downloading GitHub repo UofABioinformaticsHub/shinyNgsreports@master
Skipping 1 packages not available: shinyDirectoryInput
Installing 7 packages: shiny, shinydashboard, shinyDirectoryInput, shinyFiles, httpuv, sourcetools, fastmap
Erreur : Failed to install 'shinyNgsreports' from GitHub:
 package ‘shinyDirectoryInput’ is not available (for R version 3.6.3)

**Comment by CMWbio** [comment]
Hi lmanchon,

Thanks for finding this, it seems to be due to a mistype in the installation instructions.
Could you please try running all instructions in the readme again?

```
install.packages("BiocManager")
pkgs <- c("BiocGenerics", "BiocStyle", "BSgenome", "checkmate", "devtools", "ggdendro",  "plotly",
"reshape2", "Rsamtools", "scales", "ShortRead", "tidyverse",  "viridis", "viridisLite", "zoo", 
"mikelove/fastqcTheoreticalGC", "ngsReports", "wleepang/shiny-directory-input")
BiocManager::install(pkgs)
BiocManager::install('UofABioinformaticsHub/shinyNgsreports')

```

**Comment by lmanchon** [comment]
ok, problem is over.
The problem was due to the "shiny-directory-input" package. I compiled it separately and installed it.
Then I was able to install shinyNgsreports.
thx.
