### ISSUE TITLE
Inclusion of shiny functionality in Bioconductor package

### ISSUE THREAD

**Issue by lgeistlinger** [UofABioinformaticsHub/fastqcRShiny#6]
I find this to be a very useful package.
What were the reasons for keeping the shiny functionality separate from the `ngsReports` Bioconductor package?

One reason seems to be dependency on the two github-only packages:

* `mikelove/fastqcTheoreticalGC`
* `wleepang/shiny-directory-input`

It figures that `wleepang/shiny-directory-input` currently fails to build due to a recent change to `shiny` (https://github.com/wleepang/shiny-directory-input/issues/25), and that the CRAN package [shinyFiles](https://cran.r-project.org/web/packages/shinyFiles/index.html) would provide for a more robust alternative?

**Comment by CMWbio** [comment]
Thanks for you interest in the package and for providing a solution with your issue! I will implement it as soon as possible.  

I currently finishing up my thesis at the moment, so this fix may take a while to implement. 

- Chris

**Comment by smped** [comment]
Thanks for the really kind words @lgeistlinger! We can get rid of that mikelove import as we rewrote that step with an internal function. As to keeping it separate from Bioc, the advice we got from the the core team was to separate out this app from the package `ngsReports`. The intention was always to submit the app to Bioc, but sometimes we don't quite get around to things. If I can find time, I should revisit that.

**Comment by lgeistlinger** [comment]
Thanks, Steve.

> We can get rid of that mikelove import as we rewrote that step with an internal function.

Even better. That would mean when replacing the broken github dependency `wleepang/shiny-directory-input` by the apparently corresponding `shinyFiles` CRAN package, we'd have `shinyNgsreports` to be based on CRAN and Bioc packages only - which would make it more robust in the end. 

> the advice we got from the the core team was to separate out this app from the package ngsReports

Ok, that makes sense.

> If I can find time, I should revisit that.

I think that would be a valuable contribution.

**Comment by lgeistlinger** [comment]
Hi @steveped - I thought I quickly check in with you on the status of this. What would be really great if the package could be updated here on github to be rather based on `shinyFiles` to get rid of the breaking `wleepang/shiny-directory-input` dependency, but also of `mikelove/fastqcTheoreticalGC` by making use of your internal function for that. 

I am planning on incorporating your package in an RStudio Connect setup, where being able to install a functional version of the package via `BiocManager::install("UofABioinformaticsHub/shinyNgsreports", dependencies = TRUE)` would be very helpful.

Thanks a lot!

**Comment by smped** [comment]
Hi @lgeistlinger. Thanks for chasing this up. I'd left it in Chris's hands as the resident `shiny` guru, but given he's literally just submitted his PhD thesis & started a new position, I think he had it a bit lower on his priority list. We just had a quick chat today as a result of your reminder & he's going to have a play with tidying this up. I believe he previously had trouble with how `shinyFiles` handled some aspects of the app, such as exporting Fasta sequences. Once he's found a good workaround he'll get it up here. Thanks again! Steve

**Comment by lgeistlinger** [comment]
Excellent, many thanks for getting back at this. Happy to help where I can @CMWbio . If you welcome that, could eg provide a pull request to refactor a bit the dependency list in your `DESCRIPTION` file so we'd be able to bring in all necessary dependencies upon installation by calling:

```
BiocManager::install("UofABioinformaticsHub/shinyNgsreports")
```

ie no need to install dependencies manually by the user prior to installing `shinyNgsreports`.

**Comment by CMWbio** [comment]
@lgeistlinger 

Sorry it took so long to get around to this. It should be functional now, also added other packages to the description. 

Let me know if there is any other problems.

**Comment by lgeistlinger** [comment]
@CMWbio thanks a lot for looking into that.

```
> BiocManager::install('UofABioinformaticsHub/shinyNgsreports')
Bioconductor version 3.13 (BiocManager 1.30.15), R 4.1.0 (2021-05-18)
Installing github package(s) 'UofABioinformaticsHub/shinyNgsreports'
Downloading GitHub repo UofABioinformaticsHub/shinyNgsreports@HEAD

Running `R CMD build`...
* checking for file ‘/private/var/folders/q9/zp53ds5x6s9g62l77whflgyc0000gn/T/RtmpzEmRTf/remotes35243f76fb72/UofABioinformaticsHub-shinyNgsreports-b579cbd/DESCRIPTION’ ... OK
* preparing ‘shinyNgsreports’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘shinyNgsreports_0.99.0.tar.gz’
* installing *source* package ‘shinyNgsreports’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘shinyDirectoryInput’
```

looks like some remaining import directives in your `NAMESPACE` file that point to `shinyDirectoryInput`: https://github.com/UofABioinformaticsHub/shinyNgsreports/blob/b579cbd11216a5b3a0181cf9b7605fb2fd0f06f5/NAMESPACE#L31

I think you can get rid of them by just running `roxygen2::roxygenize` once more to update the `NAMESPACE` ...

**Comment by CMWbio** [comment]
@lgeistlinger 

Thanks for noticing this, build completed on my machine but then forgot to push the namespace!

I just successfully built from github on a fresh installation. Should be fixed up now.

**Comment by lgeistlinger** [comment]
Excellent, thanks! Closing this.
