### ISSUE TITLE
Error in .getFqcLines(from) : fl %in% allFiles is not TRUE

### ISSUE THREAD

**Issue by tobytaogla** [UofABioinformaticsHub/fastqcRShiny#7]
Hi, I try to use this package to generate a plot for several fastqc report. However, I encountered the title problem. My script is below：
> files <- list.files(path=".", pattern = "fastqc.zip$", full.names = TRUE)
> fdl <- FastqcDataList(files) 

Can you help me to solve this problem? Thanks so much!

**Comment by smped** [comment]
Hi @tobytaogla .

Can you confirm that this occurred when running the Shiny app? Or was this running as a script in an interactive R session?

Steve

**Comment by tobytaogla** [comment]
Hi, Steve. I try this directly on R. Somehow I could not install the package on R studio.

**Comment by smped** [comment]
Given that this issue doesn't appear to be related to this particular shiny app, but instead appears connected to the package `ngsReports`, can you please raise this as an issue here: https://github.com/steveped/ngsReports/issues

There seem to be several concerns going by your comment, so let's deal with them over there. When you raise this issue over there, can you please provide your `sessionInfo()` output as well?
